
action_type: table_to_table # table_to_table table_to_file or file_to_table
source_schema: test123
source_table: table123
dest_schema: final123
dest_table: finaltable123
partitioned: true
sql_query: 
source_type: postgres
dest_type: postgres